### ISSUE TITLE
ASCII Art, and Maps in game

### ISSUE THREAD

**Issue by D-W** [A-Goretsky/Byte_Me#2]
How are we going to represent maps in game in terminal with ASCII art?

**Comment by A-Goretsky** [comment]
One will be able to enter the word "map" at a point when the user is not in a fight or some activity other than exploring/progressing through the storyline. Using this sort of style: https://i.ytimg.com/vi/Lz-BKsLQ-Cg/maxresdefault.jpg

**Comment by D-W** [comment]
Oh, okay, awesome.
